# Generated by Django 5.1.4 on 2024-12-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='code',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
