version: '3'

services:
  redis:
    image: "redis:latest"
    container_name: cargo_redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

  web:
    build:
      context: .
    container_name: django_app
    command: ["/docker/one.sh"]
    volumes:
      - .:/app
      - media-data:/app/media  # Добавляем том для media
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery_worker:
    build:
      context: .
    container_name: celery_worker
    command: ["/docker/celery_worker.sh"]
    volumes:
      - .:/app
      - media-data:/app/media  # Тот же том для Celery
    depends_on:
      - redis
      - web

  celery_beat:
    build:
      context: .
    container_name: celery_beat
    command: ["/docker/celery_beat.sh"]
    volumes:
      - .:/app
      - media-data:/app/media  # Тот же том для Celery Beat
    depends_on:
      - redis
      - web

volumes:
  redis-data:
  media-data:  # Новый том для media