# Generated by Django 5.1.4 on 2024-12-23 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='branch',
        ),
    ]
