# Generated by Django 5.1.6 on 2025-02-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_remove_client_status_remove_historicalclient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='numeric_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='numeric_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
