# Generated by Django 5.1.4 on 2024-12-23 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_status_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
    ]
