# Generated by Django 5.1.4 on 2024-12-23 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
        ('products', '0004_alter_product_options_alter_status_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='branch.branch'),
        ),
    ]
