# Generated by Django 5.1.6 on 2025-02-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_historicalproduct_price_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='take_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='take_time',
            field=models.DateTimeField(null=True),
        ),
    ]
