# Generated by Django 5.1.4 on 2025-01-07 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_employeebranchaccess'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeebranchaccess',
            options={'verbose_name': 'Доступ к филиалу', 'verbose_name_plural': 'Доступ к филиалам'},
        ),
    ]
