# Generated by Django 5.1.6 on 2025-02-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_alter_employeebranchaccess_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChinaAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=255)),
                ('name2', models.CharField(max_length=100)),
                ('name3', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Адрес склада китай',
                'verbose_name_plural': 'Адрес склада китай',
            },
        ),
    ]
