# Generated by Django 5.1.6 on 2025-02-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_chinaaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chinaaddress',
            name='name1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='chinaaddress',
            name='name2',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='chinaaddress',
            name='name3',
            field=models.CharField(max_length=500),
        ),
    ]
