# Generated by Django 5.1.5 on 2025-02-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_historicalclient'),
        ('telegram', '0002_notificationimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtask',
            name='recipients',
            field=models.ManyToManyField(blank=True, to='clients.client'),
        ),
        migrations.AlterField(
            model_name='notificationimage',
            name='image',
            field=models.ImageField(upload_to='image/%Y/%m/%d/'),
        ),
    ]
