# Generated by Django 5.1.6 on 2025-02-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_historicalproduct_price_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
